M48
; DRILL file {KiCad (6.0.7)} date Mon Oct 24 20:42:32 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-10-24T20:42:32-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0236
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1693
%
G90
G05
T1
X1.6371Y-1.4712
X1.6371Y-1.6988
T2
X1.62Y-4.44
X1.63Y-2.12
X1.63Y-6.675
X6.025Y-2.12
X6.025Y-4.44
X6.025Y-6.675
T0
M30
